### ISSUE TITLE
Running the production build fails

### ISSUE THREAD

**Issue by gmanojisaac** [woudsma/retrain-mobilenet-for-the-web#1]
npm run build
serve -s build

   Serving!                                    
   │   - Local:            http://localhost:5000     │
   │   - On Your Network:  http://192.168.1.7:5000

Tried to load the production build -http://localhost:5000  && from http://192.168.1.7:5000
**The error seen in console:**
tf-core.esm.js:17 Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at tf-core.esm.js:17
    at Object.us [as decodeWeights] (tf-core.esm.js:17)
    at t.<anonymous> (tf-converter.esm.js:17)
    at tf-converter.esm.js:17
    at Object.next (tf-converter.esm.js:17)
    at o (tf-converter.esm.js:17)

**Comment by woudsma** [comment]
That is weird!
It looks like this may have something to do with the `serve` package.
Serving the production build using a different local server does not result in an error on my machine, can you confirm?
```sh
git clone https://github.com/woudsma/retrain-mobilenet-for-the-web \
  && cd retrain-mobilenet-for-the-web \
  && npm install \
  && npm run build

http-server build
# Or
php -S localhost:5000 -t build
```

**Comment by davenep** [comment]
I am having the same problem when I run in http://localhost:3000/.

Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at o (tf-core.esm.js:11735)
    at Object.decodeWeights (tf-core.esm.js:11749)
    at e.<anonymous> (tf-converter.esm.js:6377)
    at tf-converter.esm.js:133
    at Object.next (tf-converter.esm.js:146)
    at s (tf-converter.esm.js:33)

**Comment by woudsma** [comment]
@davenep Using what package/software/tool are you hosting the app locally?
If you're using `serve`, see my answer above, but i'll try to find out what causes this strange error.

**Comment by davenep** [comment]
@woudsma I rechecked the folder structure and found that the shard file was missing. I copied the shard files manually and it has started working in the local server. However uploading the build to the webhost still shows the same error,,maybe the shard files are not loaded in the web server??

**Comment by woudsma** [comment]
@davenep Can you give some specifics on your web host setup? I think this error might have something to do with compression when transferring the files from/to the host.

These issues could be related to your issue:
https://github.com/tensorflow/tfjs/issues/218
https://github.com/potree/potree/issues/68

**Comment by davenep** [comment]
@woudsma The solution mentioned in potree/potree#68 by m-schuetz "This happens quite frequently to users who upload the data with FileZilla and transfer mode set to auto or ascii. If that's the case, go to Edit->Settings->Transfers->File Types and set the default transfer type to Binary." worked for me. Thank you!
