### ISSUE TITLE
Time to execute in mobile chrome-Galaxy J7 takes 10 times as much as in Laptop broswer

### ISSUE THREAD

**Issue by gmanojisaac** [woudsma/retrain-mobilenet-for-the-web#2]
Time to execute in Desktop - 100ms
Time to execute in Mobile - 5000ms.

![desktop 100ms](https://user-images.githubusercontent.com/16835712/45595067-79eaea80-b9c3-11e8-9e86-5c996c069f17.jpg)
![mobile 5000ms](https://user-images.githubusercontent.com/16835712/45595068-79eaea80-b9c3-11e8-989a-97270e0f5b21.jpeg)

User satisfaction will become less

**Comment by woudsma** [comment]
When picking a MobileNet version/module, you have to consider the model input size.
Larger models (224x244px, such as in the example) run slower on mobile devices.
Running inference using the demo app takes ~200-300ms on my iPhone 6.
I've tested the performance of the demo app on a Samsung Galaxy S7, which takes ~400-500ms.

You could pick a module which is optimized for slower devices, such as the pre-trained 96x96px model.
Also you have to take in account, getting the first prediction can take longer than subsequent predictions. You may find speedup in subsequent calls to `model.predict()`.
I hope this clears things up.
